Simulation += Simulation_data.o Simulation_init.o Simulation_initBlock.o outtotecplot.o sim_trackBubble.o mph_bcLevelSet.o \
	      ins_imbound.o ib_distributedFluxes.o

Simulation_init.o : Simulation_data.o 
Simulation_initBlock.o : Simulation_data.o
ins_imbound.o: ins_imbound.o
ib_distributedFluxes.o: ib_distributedFluxes.o
