#!/bin/bash

if [ $1 = "build" ]; then

    docker pull akashdhruv/flash:4.0

    docker run -dit --name flash_container -v $PWD:/home/FLASH -v ~/Desktop/run:/home/run akashdhruv/flash:4.0

    docker exec -it flash_container bash
fi

if [ $1 = "reset" ]; then

    docker stop flash_container

    docker rm -f flash_container

fi
 
if [ $1 = "clean" ]; then

    docker stop flash_container

    docker rm -f flash_container

    docker rmi -f akashdhruv/flash:4.0

    docker system prune -a
fi
