#!/bin/bash

source maple.config

if [ $1 = "build" ]; then
docker build -t $maple_container --build-arg flash_object=$flash_object \
                                 --build-arg flash_run_files=$flash_run_files \
                                 --build-arg flash_path=$flash_path \
                                 --file docker/Dockerfile .
fi

if [ $1 = "rebuild" ]; then
docker build -t $maple_container --build-arg flash_object=$flash_object \
                                 --build-arg flash_run_files=$flash_run_files \
                                 --build-arg flash_path=$flash_path \
                                 --file docker/Dockerfile .
fi

if [ $1 = "run" ]; then
docker run -v $2:/home/run/IOData $maple_container
fi

if [ $1 = "clean" ]; then
docker rmi -f $maple_container
fi
