Plasma += Plasma_computeDtLocal.o Plasma_computeDt.o Plasma_get_reactions.o \
          Plasma_Solve.o Plasma_hvDiffCoeff.o Plasma_elDiffCoeff.o \
          Plasma_ColFreq.o Plasma_sumNeutrals.o Plasma_sumIons.o \
          Plasma_spReactions.o Plasma_spGeneration.o Plasma_Feed.o \
          Plasma_netCharge.o Plasma_elPotential.o

