Heat += Heat_AD_interface.o Heat_AD_data.o Heat_AD_init.o Heat_AD_finalize.o \
	Heat_RHS_upwind.o Heat_Solve.o Heat_calGradT.o Heat_calGradT_central.o Heat_extrapGradT.o \
	Heat_calMdot.o Heat_AD.o Heat_RHS_central.o Heat_RHS_weno3.o\
        Heat_RHS_3D.o Heat_RHS_3D_weno3.o Heat_calGradT_3D.o Heat_extrapGradT_3D.o \
	Heat_calGradT_3D_central.o Heat_GFMstencil.o Heat_extrapGradT_weno3.o Heat_getQmicro.o
