#!/bin/sh -f

#		Script to create a subroutine which writes a 'build stamp'
#		to the log file

rm -f setup_buildstamp.F90
echo '      ' subroutine setup_buildstamp \(s_stamp_str, b_stamp_str, str_len\) >> setup_buildstamp.F90
echo '      ' implicit none >> setup_buildstamp.F90
echo '      ' integer                  :: str_len >> setup_buildstamp.F90
echo '      ' character\(len=str_len\) :: s_stamp_str, b_stamp_str >> setup_buildstamp.F90
echo '      ' s_stamp_str = \'Thu Jun 10 12:32:34 2021\'  >> setup_buildstamp.F90
echo '      ' b_stamp_str = \'`date '+%a %b %e %H:%M:%S %Y'`\'  >> setup_buildstamp.F90
echo '      ' return >> setup_buildstamp.F90
echo '      ' end subroutine >> setup_buildstamp.F90
echo '      ' >> setup_buildstamp.F90
echo '      ' subroutine setup_systemInfo \(system_str, str_len\) >> setup_buildstamp.F90
echo '      ' integer                  :: str_len >> setup_buildstamp.F90
echo '      ' character\(len=str_len\) :: system_str >> setup_buildstamp.F90
echo '      ' system_str = "'Linux&
& pfe23&
& 4.12.14-122.66.2.20210415-nasa&
& #1 SMP Mon Apr 12 10:54:37 UTC 2021 (8fc5925)&
& x86_64'"  >> setup_buildstamp.F90
echo '      ' return >> setup_buildstamp.F90
echo '      ' end subroutine >> setup_buildstamp.F90
echo '      ' >> setup_buildstamp.F90

