Timers = Timers_getSummary.o \
	Timers_init.o \
	Timers_reset.o \
	Timers_start.o \
	Timers_stop.o \
	Timers_finalize.o Timers_interface.o

Timers += Timers_data.o \
	tmr_create.o \
	tmr_etime.o \
	tmr_init.o \
	tmr_lookupIndex.o \
	tmr_stackLib.o \
	tmr_buildSummary.o \
	tmr_findTimerIndex.o \
	tmr_getMaxTimerParents.o \
	tmr_getMaxCallStackDepth.o \
	Timers_getSummary.o
